<header>
  <nav>
    <ul>
      <li><a href="$base$/" title="home"><img src="$base$/img/home.svg"></a></li>
      <li><a href="$base$/Tech" title="Technology"><img src="$base$/img/tech.svg"></a></li>
      <li><a href="$base$/Travel" title="Travel"><img src="$base$/img/travel.svg"></a></li>
      <li><a href="$base$/Cooking" title="Cooking"><img src="$base$/img/cooking.svg"></a></li>
      <li class="edit"><a href="$base$/_edit$pageUrl$"><img src="$base$/img/edit.svg"></a></li>
      <li class="search">
      $search()$
      </li>
    </ul>
  </nav>
</header>
