<div class="tool-category">
  <fieldset>
    <legend>Other Sites</legend>
    <ul>
      <li><a href="https://github.com/mmakowski">Github</a></li>
      <li><a href="http://www.flickr.com/photos/mmakowski/">Flickr</a></li>
      <li><a href="http://www.last.fm/user/mmakowski">Last.fm</a></li>
      <li><a href="http://www.linkedin.com/in/mmakowski">LinkedIn</a></li>
      <li><a href="http://mmakowski.com/dp/">Der Preßlufthammer</a></li>
      <li><a href="http://mmakowski.com/matex95a/">Matex 95a</a></li>
    </ul>
  </fieldset>
</div>
